name: flights
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip==20.2.2
  - ipykernel==5.3.4
  - flake8==3.8.3
  - pre-commit==2.7.1
  - pytest==6.0.1
  - pytest-cov==2.8.1
  - sphinx==3.2.1
  - black==19.10b0
  - conda-forge::nodejs=14.2.0
  - jupyterlab==2.2.5
  - jupytext==1.5.2
  - pandas==1.1.1
  - numpy==1.19.1
  - setuptools==49.6.0
  - fsspec
  - s3fs==0.5.2
  - aiobotocore[boto3]
  - pip:
    - ipywidgets==7.5.1
    - scikit-learn==0.24.0
    - xgboost==1.2.0
    - seaborn==0.11.1
    - statsmodels==0.12.2
    - pandas-profiling==2.11.0